[package]
name = "geometric_algebra"
version = "0.1.0"
authors = ["Alexander Mei√üner <AlexanderMeissner@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd = { path = "simd" }
